#server:
#  port: 8080
#
#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    email: ninhduydang2001@gmail.com
#    password: vhzg ugqv ssta pqjl
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connection-timeout: 5000
#          timeout: 3000
#          write timeout: 5000

server:
  port: 8080
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ninhduydang2001@gmail.com
    password: vhzg ugqv ssta pqjl
    properties:
      mail:
        smtp:
          auth: true  # Bật chứng thực SMTP
          starttls:
            enable: true  # Bật STARTTLS
          ssl:
            trust: "*"  # Tùy chọn, bạn có thể giữ nguyên hoặc loại bỏ
          connection-timeout: 5000
          timeout: 3000
          write timeout: 5000



